import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MessageProvider } from "../services/message";
import { ImageProvider } from "../services/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Storyteller GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImageProvider>
          <MessageProvider>{children}</MessageProvider>
        </ImageProvider>
      </body>
    </html>
  );
}
